twig:
    default_path: '%kernel.project_dir%/templates'

when@dev:
    twig:
        strict_variables: true
        default_path: '%kernel.project_dir%/tests/templates'

when@test:
    twig:
        strict_variables: true
        default_path: '%kernel.project_dir%/tests/templates'
